query GetProduct($handle: String!) {
  products(first: 1, query: $handle) {
    edges {
      node {
        id
        title
        descriptionHtml
        handle
        media(first: 10, sortKey: POSITION) {
          nodes {
            ... on MediaImage {
              id
              mediaContentType
              image {
                id
                url
                altText
                width
                height
              }
            }
          }
        }
        variants(first: 10) {
          edges {
            node {
              id
              title
              availableForSale
              quantityAvailable
              selectedOptions {
                name
                value
              }
              price {
                amount
                currencyCode
              }
              sku
            }
          }
        }
      }
    }
  }
}